//! The local library's data model.
//!
//! Two shapes, and the difference between them is the whole design:
//!
//! - A [`LocalSource`] is *one import*. On desktop that is a directory path; on
//!   Android it is a SAF tree grant, or a set of per-file grants. It can go
//!   `available: false` — a revoked grant, an unmounted card, a moved folder —
//!   and that is a state, never a reason to delete anything. A user who spent an
//!   evening building local playlists must not lose them because a card was out
//!   when the app started.
//! - A [`LocalTrack`] is one file, keyed by its *locator* — the absolute path or
//!   the `content://` document URI. That key is what `TrackIdentity::Local`
//!   carries, what local playlists store, and what the favourite set holds.

use serde::{Deserialize, Serialize};

/// How a source was imported.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum SourceKind {
    /// A directory (desktop path, or an Android SAF tree grant). One grant
    /// covers everything beneath it, which is why this is the preferred shape:
    /// Android caps the number of persisted grants per app.
    Directory,
    /// Individually picked files. Each one costs a grant on Android.
    Files,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct LocalSource {
    /// Derived from the locator, not random: re-importing the same folder maps
    /// onto the same source instead of duplicating it.
    pub id: String,
    pub kind: SourceKind,
    /// Absolute path, or `content://…/tree/…`.
    pub locator: String,
    pub display_name: String,
    /// Whether the source was reachable at the last check. Reconciled at
    /// startup; a `false` here hides nothing and deletes nothing.
    #[serde(default = "default_true")]
    pub available: bool,
    /// Unix seconds. 0 means "never scanned".
    #[serde(default)]
    pub last_scanned_at: i64,
    /// Cached count so the source list does not have to walk the track table.
    #[serde(default)]
    pub track_count: usize,
    /// For `Files` sources: the individual document URIs the user granted.
    /// Empty for directories, whose members come from the walk.
    #[serde(default)]
    pub members: Vec<String>,
}

fn default_true() -> bool {
    true
}

/// One indexed file.
///
/// Field order matters for `bincode`, which is a positional format: adding a
/// field anywhere but the end, or reordering, invalidates every existing index.
/// That is survivable (the index is regenerated by re-scanning) but it must be
/// deliberate — see [`crate::local::index::LIBRARY_VERSION`].
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct LocalTrack {
    /// The locator. The one durable identity: everything else about a file can
    /// change when it is re-tagged.
    pub key: String,
    /// The negative id the frontend's `SongData.id` carries. Assigned here and
    /// only here — see [`crate::local::index::local_song_id`].
    pub song_id: i64,
    pub source_id: String,
    pub title: String,
    pub artist: String,
    pub album: String,
    pub album_artist: String,
    pub duration_ms: u64,
    pub sample_rate: u32,
    pub channels: u16,
    pub bitrate_bps: Option<u64>,
    pub codec: String,
    pub track_no: Option<u32>,
    pub disc_no: Option<u32>,
    pub year: Option<i32>,
    pub size: Option<u64>,
    /// Unix seconds, from the filesystem or the document provider. Half of the
    /// incremental-scan check; the other half is `size`.
    pub modified_at: Option<i64>,
    /// Filename of the extracted cover under the cover cache directory.
    pub cover_key: Option<String>,
    /// Whether this source must be spooled to a file before it can be decoded
    /// (a pipe-backed document provider). Surfaced so the UI can say so.
    #[serde(default)]
    pub needs_cache: bool,
    /// Filename. The fallback title, and the only place an extension survives.
    pub display_name: String,
    /// Directory this file sits in, relative to its source root. Drives the
    /// "by folder" grouping; empty for a `Files` source.
    #[serde(default)]
    pub relative_dir: String,
    /// Locator of a sibling `.lrc` / `.ttml`, found during the same walk.
    #[serde(default)]
    pub lyric_key: Option<String>,
}

impl LocalTrack {
    /// The artist to group by. Falls back to the track artist, because plenty of
    /// files carry no album artist at all and grouping those under one empty
    /// bucket is worse than splitting a compilation.
    pub fn grouping_artist(&self) -> &str {
        if self.album_artist.trim().is_empty() {
            &self.artist
        } else {
            &self.album_artist
        }
    }

    /// Whether a re-scan can skip this file. Both halves matter: a file edited
    /// in place keeps its size often enough that mtime alone would miss it, and
    /// a filesystem that reports no mtime would make size alone the only signal.
    ///
    /// A row whose *derived* fields are stale is never skippable, however
    /// untouched the file is — see [`Self::has_stale_derived_fields`]. Without
    /// that, a fix to how something is derived would only ever reach tracks the
    /// user happened to edit afterwards, because an incremental scan exists
    /// precisely to not re-probe anything.
    pub fn unchanged(&self, size: Option<u64>, modified_at: Option<i64>) -> bool {
        self.size.is_some()
            && self.size == size
            && self.modified_at == modified_at
            && !self.has_stale_derived_fields()
    }

    /// Whether anything on this row was derived by code we have since fixed.
    ///
    /// Currently one case: `codec` used to be `format!("{:?}", codec_type)`, which
    /// produced `codectype(4099)` — Symphonia's newtype `Debug`, not a name. The
    /// string is recognisable, so a row carrying one can be re-probed on the next
    /// scan instead of asking every user to press 重新读取 on each track.
    ///
    /// Cheap on purpose: this runs once per candidate per scan, in the loop that
    /// decides what to probe at all.
    pub fn has_stale_derived_fields(&self) -> bool {
        self.codec.starts_with("codectype")
    }
}

/// A user's edit to one track's tags.
///
/// **Overrides, not writes.** The audio file is never modified: symphonia is a
/// read-only decoder, Android grants us `READ` on a SAF tree and nothing more,
/// and a failed tag write corrupts the one copy of a song the user has. So a
/// correction lives here and is layered over the scanned row on the way out.
///
/// Lives in `local-user-data.json` rather than in the `bincode` index for the
/// same reason favourites do: a re-scan replaces track rows wholesale, and an
/// edit nobody can reconstruct must survive that. Every field is `Option`, and
/// `None` means "use what the file said" — which is what makes "revert" simply
/// dropping the entry.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct TrackOverride {
    #[serde(default)]
    pub title: Option<String>,
    #[serde(default)]
    pub artist: Option<String>,
    #[serde(default)]
    pub album: Option<String>,
    #[serde(default)]
    pub album_artist: Option<String>,
    #[serde(default)]
    pub track_no: Option<u32>,
    #[serde(default)]
    pub disc_no: Option<u32>,
    #[serde(default)]
    pub year: Option<i32>,
    /// Unix seconds. Shown in the UI so an edit is visibly *yours*.
    #[serde(default)]
    pub updated_at: i64,
}

impl TrackOverride {
    /// Whether anything is actually overridden. An entry that answers `false`
    /// here is dropped rather than stored, so "revert everything" and "never
    /// edited" are the same state on disk.
    pub fn is_empty(&self) -> bool {
        self.title.is_none()
            && self.artist.is_none()
            && self.album.is_none()
            && self.album_artist.is_none()
            && self.track_no.is_none()
            && self.disc_no.is_none()
            && self.year.is_none()
    }

    /// Layer this override over a scanned row.
    ///
    /// Applied *before* filtering, sorting and grouping — not just when building
    /// the row the UI shows. Otherwise a corrected album name would appear on the
    /// track but the album list would still group by the file's tag, and a keyword
    /// search would not find what the user can see.
    pub fn apply(&self, track: &mut LocalTrack) {
        if let Some(title) = &self.title {
            track.title = title.clone();
        }
        if let Some(artist) = &self.artist {
            track.artist = artist.clone();
        }
        if let Some(album) = &self.album {
            track.album = album.clone();
        }
        if let Some(album_artist) = &self.album_artist {
            track.album_artist = album_artist.clone();
        }
        if let Some(track_no) = self.track_no {
            track.track_no = Some(track_no);
        }
        if let Some(disc_no) = self.disc_no {
            track.disc_no = Some(disc_no);
        }
        if let Some(year) = self.year {
            track.year = Some(year);
        }
    }
}

/// How a lyric file should be parsed.
///
/// Deliberately coarse: the frontend already detects YRC vs QRC vs ESLrc from
/// the *content* (`detectWordTimedLyricFormat`), and duplicating that detection
/// in Rust would be a second implementation of one rule — the trap
/// `identity.ts` ↔ `TrackIdentity::key()` already documents. So this only says
/// which family the extension claimed, and a mislabelled file still renders
/// because the frontend re-checks.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum LyricKind {
    /// Plain line-timed LRC.
    Lrc,
    /// Word-timed: NCM YRC, QQ QRC, or ESLrc. The frontend picks the parser.
    Word,
    /// Apple-style TTML.
    Ttml,
}

impl LyricKind {
    /// Family for a file extension. Anything unrecognised is treated as LRC,
    /// which is the format that degrades best — a word-timed file read as LRC
    /// still shows lines, and the frontend's content check will correct it.
    pub fn from_extension(ext: &str) -> Self {
        match ext.trim().trim_start_matches('.').to_ascii_lowercase().as_str() {
            "ttml" | "xml" => LyricKind::Ttml,
            "yrc" | "qrc" | "eslrc" => LyricKind::Word,
            _ => LyricKind::Lrc,
        }
    }
}

/// A lyric file the user imported for one track.
///
/// The text is **not** stored here: this record goes in
/// `local-user-data.json`, which is rewritten whenever a favourite is toggled,
/// and a few thousand lines of TTML per track would turn one heart press into a
/// multi-megabyte write. The text lives in its own file under
/// `$APPDATA/local-lyrics/`.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct LyricImport {
    /// Filename under the lyric directory.
    pub file: String,
    pub kind: LyricKind,
    /// What the user picked it from, for display.
    #[serde(default)]
    pub original_name: String,
    #[serde(default)]
    pub imported_at: i64,
}

/// Translation and romanisation for one track, alongside whatever its main lyric
/// turns out to be.
///
/// Deliberately **not** part of [`LyricImport`]. These never render on their own —
/// the frontend's parser aligns them onto the main lyric's lines — so they are
/// additive to whichever source `local_lyric_for` settles on, and a record holding
/// only companions must not be mistaken for an import the *user* made, which
/// outranks every other source by design.
///
/// Written by the download queue, where they arrive with the lyric and would
/// otherwise be dropped: Netease serves them as separate documents, and an audio
/// container has nowhere to put a second and third lyric that our own reader could
/// tell apart again (symphonia folds every `USLT` into one field).
///
/// Same split as the records above — the filenames are here, the text is next to
/// them under `$APPDATA/local-lyrics/`.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct LyricCompanions {
    /// Filename holding the translation, if there is one.
    #[serde(default)]
    pub translation: Option<String>,
    /// Filename holding the romanisation, if there is one.
    #[serde(default)]
    pub romanisation: Option<String>,
    #[serde(default)]
    pub stored_at: i64,
}

impl LyricCompanions {
    pub fn is_empty(&self) -> bool {
        self.translation.is_none() && self.romanisation.is_none()
    }
}

/// Cover art the user picked for one track.
///
/// Same split as [`LyricImport`], and for the same reason: the record goes in
/// `local-user-data.json`, which is rewritten on every favourite toggle, so the
/// picture itself stays a file. It goes in the *same* `local-covers/` directory
/// as the scanned art — that directory is the one named in `tauri.conf.json`'s
/// `assetProtocol.scope`, so it is the only place `convertFileSrc` can reach —
/// and it is content-addressed by `cover::store`, so a cover applied to twelve
/// tracks of an album is one file on disk.
///
/// Because it does not live on a track row, `cover::prune` cannot see it from the
/// tracks alone; [`super::index::LocalIndex::referenced_cover_files`] is what
/// keeps a re-scan from deleting it.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CoverImport {
    /// Filename under the cover directory.
    pub file: String,
    /// What the user picked it from, for display.
    #[serde(default)]
    pub original_name: String,
    #[serde(default)]
    pub imported_at: i64,
}

/// A user-built local playlist.
///
/// Holds *keys*, not tracks. A re-scan replaces track rows wholesale; if a
/// playlist held copies, every re-scan would either strand them or need a merge
/// pass, and a renamed tag would silently drop a song out of a playlist.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct LocalPlaylist {
    pub id: String,
    pub name: String,
    #[serde(default)]
    pub description: String,
    #[serde(default)]
    pub created_at: i64,
    #[serde(default)]
    pub updated_at: i64,
    /// Track keys, in user order.
    #[serde(default)]
    pub tracks: Vec<String>,
    /// Where an imported playlist came from, for display. `None` for one the
    /// user created in-app.
    #[serde(default)]
    pub imported_from: Option<String>,
}

/// Progress for a running scan. Pushed over a `tauri::ipc::Channel`.
#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct ScanProgress {
    pub source_id: String,
    /// `listing` → `tagging` → `done` (or `failed`).
    pub phase: &'static str,
    pub done: usize,
    pub total: usize,
    /// The file being read, for the progress line. Display name, not a path:
    /// a `content://` URI is not something to show a person.
    pub current: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
}
