//! In-process NeteaseCloudMusic protocol layer.
//!
//! A QuickJS isolate hosting the upstream endpoint scripts (see
//! `scripts/build-ncm-protocol.mjs`) over Rust crypto, compression and HTTP
//! primitives. The JS half owns *protocol* logic — which fields go in which
//! weapi/eapi/xeapi envelope — because that is the half that changes upstream.
//! Everything stable lives in `ops.rs`.
//!
//! Why this exists: the app previously reached Netease through a deployed
//! NeteaseCloudMusicApi instance, which costs a full extra network hop on every
//! call (measured at ~38–48 ms). Running the same protocol code in-process
//! collapses that to a direct request. See
//! `docs/native-ncm-api-embedding-plan.md`.
//!
//! ## Concurrency
//!
//! The runtime is async, and [`NcmCore`] is `Send + Sync`, so it can be shared
//! directly rather than hidden behind a worker thread.
//!
//! JS execution is still serialized — QuickJS holds one runtime lock — but the
//! HTTP op returns a real promise, so requests overlap. That distinction is the
//! whole reason this is async: a page load fans out a dozen endpoint calls, and
//! with a blocking client they would run one after another (~90 ms each),
//! giving back far more than the hop this crate removes. The crypto that
//! actually holds the lock is single-digit milliseconds.
//!
//! Overlapping is not the same as unlimited: Netease refuses a burst rather
//! than queueing it, so [`crate::throttle`] caps how much of that overlap
//! actually reaches the wire. See that module for the measurements.
//!
//! ## Secrets
//!
//! Cookies are passed in per call and are never persisted here, never logged,
//! and never included in an error. [`redact`] is the last line of defence for
//! anything that reaches a log.

mod batch;
mod cache;
mod disk;
mod http;
mod inflight;
mod ops;
mod state;
mod throttle;

use std::path::PathBuf;
use std::sync::{Arc, Mutex};

use rquickjs::{AsyncContext, AsyncRuntime, Function, Object, Promise};

pub use state::StateStore;

/// The bundled protocol layer. Generated by `pnpm build:ncm-protocol` and
/// committed, so a plain `cargo build` never needs Node.
const PROTOCOL_JS: &str = include_str!("../js/ncm-protocol.js");

/// Identifies the bundle, for [`StateStore::BOOTSTRAP_VERSION`].
///
/// The bundle's byte length rather than its version string: the version lives
/// inside `PROTOCOL_JS` and would have to be parsed out, while any regeneration
/// that changes the handshake also changes the length. A collision would only
/// mean one skipped re-handshake against a bundle whose xeapi key still works,
/// which is where a version match leaves us anyway.
fn protocol_build() -> String {
    PROTOCOL_JS.len().to_string()
}

/// Cap the isolate's heap. The protocol layer works on small JSON payloads;
/// anything approaching this is a runaway response, and failing the call beats
/// letting one endpoint balloon the process.
const MEMORY_LIMIT: usize = 64 * 1024 * 1024;

#[derive(Debug)]
pub enum NcmError {
    /// The isolate could not be created or the bundle failed to evaluate.
    Init(String),
    /// The call reached JS but the isolate raised.
    Script(String),
}

impl std::fmt::Display for NcmError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            NcmError::Init(m) => write!(f, "ncm-core init failed: {m}"),
            NcmError::Script(m) => write!(f, "ncm-core script error: {m}"),
        }
    }
}

impl std::error::Error for NcmError {}

pub struct NcmCore {
    // Field order is load-bearing: the context must drop before the runtime.
    context: AsyncContext,
    _runtime: AsyncRuntime,
    /// Shared with the background refreshes spawned by [`NcmCore::call`], which
    /// outlive the call that started them.
    cache: Arc<cache::ResponseCache>,
    inflight: inflight::Inflight,
    batcher: Arc<batch::Batcher>,
    /// Held to read the transport's health before starting speculative work.
    http: Arc<http::HttpClient>,
    /// Permits for work nobody is waiting for — prefetches and stale refreshes.
    ///
    /// This is what makes speculation safe to turn on. A host gives out
    /// [`throttle::MAX_IN_FLIGHT`] slots and [`crate::throttle::HostGate::admit`]
    /// is first-come-first-served, so without a cap of its own a burst of
    /// prefetches would sit in front of the request the user is actually waiting
    /// for. Bounding it well below the ceiling leaves the foreground a clear
    /// majority of the concurrency at all times.
    ///
    /// A permit is *tried*, never awaited: speculative work that cannot start
    /// immediately is dropped rather than queued. Something nobody is waiting
    /// for has no business being in a queue, and by the time it reached the
    /// front the guess it was based on is usually stale anyway.
    speculation: Arc<tokio::sync::Semaphore>,
}

/// Concurrent prefetches and background refreshes.
///
/// Four, against a per-host ceiling of six. Sized to what one track change
/// actually hints — the next couple of tracks' lyric and detail — because a
/// permit is what lets a hint *enter* the batcher, and a hint that cannot get one
/// is dropped. At two, a three-track hint set reliably lost one and the real call
/// for it paid a round trip, which defeats the point.
///
/// Raising it is cheaper than it looks: hints for the same endpoint merge, so
/// four `song_detail` hints are one request, not four. The bound that matters for
/// the wire is [`crate::batch`] plus the host gate; this one only stops unbounded
/// fan-out. Still comfortably below the ceiling, so the foreground always has
/// connections spare.
const MAX_SPECULATION: usize = 4;

impl NcmCore {
    /// Create an isolate. `state_dir`, when given, is where `anonymous_token`
    /// and the cached xeapi public key are persisted between launches.
    ///
    /// When that state is cold this performs the upstream `generateConfig`
    /// handshake (two network round trips) before returning. A failed bootstrap
    /// is logged, not fatal: authenticated calls carry their own cookie and
    /// work without it.
    pub async fn new(state_dir: Option<PathBuf>) -> Result<Self, NcmError> {
        Self::build(state_dir, true).await
    }

    /// Create an isolate without the cold-start handshake, and without any
    /// network I/O.
    ///
    /// For tests and offline diagnostics. xeapi endpoints — including
    /// `song_url_v1` — cannot work on an isolate built this way, because they
    /// need the server's public key.
    pub async fn offline() -> Result<Self, NcmError> {
        Self::build(None, false).await
    }

    async fn build(state_dir: Option<PathBuf>, bootstrap: bool) -> Result<Self, NcmError> {
        let runtime = AsyncRuntime::new().map_err(|e| NcmError::Init(e.to_string()))?;
        runtime.set_memory_limit(MEMORY_LIMIT).await;
        // A future spawned into the isolate is only polled while some
        // `async_with` is being polled, and the schedular keeps a single waker
        // for the whole runtime — so a promise that outlives the call that
        // created it has nothing driving it. `drive` is rquickjs's answer:
        // it holds a durable subscription and completes on its own when the
        // runtime drops, which is why it can be spawned and forgotten.
        tokio::spawn(runtime.drive());

        // Built before the bootstrap handshake, so a launch that comes up
        // offline still has last session's answers to serve.
        let cache = Arc::new(cache::ResponseCache::new(state_dir.as_deref()));
        // Bringing the directory inside its bounds walks it, so it happens off
        // the startup path. Nothing waits on it: an over-budget cache is only
        // over budget, not wrong.
        //
        // `spawn_blocking`, not `spawn`: the walk is `read_dir` plus a `metadata`
        // and a header read per entry — hundreds of synchronous filesystem calls
        // — and it runs at the moment the first screen is fanning a dozen
        // requests out, so an async worker is the one thing it must not sit on.
        {
            let cache = cache.clone();
            tokio::task::spawn_blocking(move || cache.prune_disk());
        }

        let http = Arc::new(http::HttpClient::new());
        let store = Arc::new(Mutex::new(match state_dir {
            Some(dir) => StateStore::persisted(dir),
            None => StateStore::in_memory(),
        }));

        // `util/request.js` snapshots `anonymous_token` into a module-level
        // const when it is first required, so a token fetched inside this
        // context would not be seen by it. Bootstrap therefore runs in a
        // throwaway context and the real one is built afterwards, against warm
        // state. (The xeapi public key is read lazily upstream and would not
        // need this, but sharing one path keeps the ordering obvious.)
        //
        // "Cold" is whether the handshake has ever *run* to completion for this
        // bundle, not whether both values it can produce are present. Netease
        // routinely answers `register_anonimous` without a `MUSIC_A`, so the
        // token often never lands — and testing for its presence meant every
        // launch spent two requests and ~350 ms re-running the handshake to fail
        // at the same step. The xeapi key is still required, because xeapi
        // endpoints genuinely cannot work without it.
        let cold = match store.lock() {
            Ok(s) => {
                s.get("xeapi_public_key").is_none()
                    || s.get(StateStore::BOOTSTRAP_VERSION).as_deref() != Some(protocol_build().as_str())
            }
            Err(_) => true,
        };
        if bootstrap && cold {
            let boot = AsyncContext::full(&runtime)
                .await
                .map_err(|e| NcmError::Init(e.to_string()))?;
            let http = http.clone();
            let boot_store = store.clone();
            let outcome = boot
                .async_with(async move |ctx| -> Result<String, String> {
                    ops::install(&ctx, http, boot_store).map_err(|e| explain(&ctx, e))?;
                    ctx.eval::<(), _>(PROTOCOL_JS).map_err(|e| explain(&ctx, e))?;
                    let proto: Object = ctx
                        .globals()
                        .get("__ncmProtocol")
                        .map_err(|e| explain(&ctx, e))?;
                    let f: Function = proto.get("bootstrap").map_err(|e| explain(&ctx, e))?;
                    let promise: Promise = f
                        .call((rquickjs::function::This(proto),))
                        .map_err(|e| explain(&ctx, e))?;
                    promise
                        .into_future::<String>()
                        .await
                        .map_err(|e| explain(&ctx, e))
                })
                .await;
            match outcome {
                Ok(report) => {
                    log::info!(target: "ncm-core", "bootstrap: {report}");
                    // Recorded only when the handshake actually ran, and only if
                    // it produced the key that endpoints need. An anonymous
                    // token Netease declined to issue is not a reason to keep
                    // asking on every launch.
                    if let Ok(mut s) = store.lock() {
                        if s.get("xeapi_public_key").is_some() {
                            s.set(StateStore::BOOTSTRAP_VERSION, protocol_build());
                        }
                    }
                }
                Err(e) => log::warn!(target: "ncm-core", "bootstrap failed: {e}"),
            }
        }

        let context = AsyncContext::full(&runtime)
            .await
            .map_err(|e| NcmError::Init(e.to_string()))?;
        let installed = http.clone();
        context
            .async_with(async move |ctx| -> Result<(), String> {
                ops::install(&ctx, installed, store).map_err(|e| explain(&ctx, e))?;
                ctx.eval::<(), _>(PROTOCOL_JS).map_err(|e| explain(&ctx, e))?;
                Ok(())
            })
            .await
            .map_err(NcmError::Init)?;

        Ok(Self {
            context,
            _runtime: runtime,
            cache,
            inflight: inflight::Inflight::new(),
            batcher: Arc::new(batch::Batcher::new()),
            http,
            speculation: Arc::new(tokio::sync::Semaphore::new(MAX_SPECULATION)),
        })
    }

    /// Endpoint names the bundle exposes (upstream module basenames, e.g.
    /// `song_url_v1`).
    pub async fn endpoints(&self) -> Result<Vec<String>, NcmError> {
        self.context
            .async_with(async |ctx| -> Result<Vec<String>, String> {
                let proto: Object = ctx
                    .globals()
                    .get("__ncmProtocol")
                    .map_err(|e| explain(&ctx, e))?;
                proto.get("endpoints").map_err(|e| explain(&ctx, e))
            })
            .await
            .map_err(NcmError::Script)
    }

    /// Version of the upstream package the bundle was built from.
    pub async fn protocol_version(&self) -> Result<String, NcmError> {
        self.context
            .async_with(async |ctx| -> Result<String, String> {
                let proto: Object = ctx
                    .globals()
                    .get("__ncmProtocol")
                    .map_err(|e| explain(&ctx, e))?;
                proto.get("version").map_err(|e| explain(&ctx, e))
            })
            .await
            .map_err(NcmError::Script)
    }

    /// Invoke an endpoint.
    ///
    /// `query_json` is the request parameters as a JSON object, including
    /// `cookie` when the call is authenticated. The return is a JSON string:
    ///
    /// ```json
    /// { "ok": true, "status": 200, "body": { ... }, "cookie": ["..."] }
    /// ```
    ///
    /// A non-200 upstream response is **not** an `Err` — it comes back with
    /// `ok: false` and the upstream body intact, because callers act on
    /// in-band codes like 301 (not logged in). `Err` is reserved for the
    /// isolate itself failing.
    ///
    /// ## Four ways a call can avoid the network
    ///
    /// All of them are here because of one measurement: the isolate costs ~12 µs
    /// per call and a 1.5 MB JSON round trip through QuickJS costs ~7 ms, while
    /// one warm request to Netease costs ~80 ms and one that has to open a
    /// connection first costs ~190 ms. Nothing on this side of the socket is
    /// worth optimizing; only the number of round trips is.
    ///
    /// * [`crate::cache`] answers from a response already held, in memory or on
    ///   disk from a previous launch. An answer past its TTL but inside its
    ///   stale window is still served — immediately — and refreshed behind the
    ///   caller, which is what makes re-opening a view after a long idle stretch
    ///   cost nothing instead of a reconnect.
    /// * [`crate::batch`] merges calls that differ only by id — twenty song
    ///   cards rendering at once become one `song_detail`.
    /// * [`crate::inflight`] shares one request between callers asking for the
    ///   same thing at the same time, which the cache cannot do because the
    ///   answer has not arrived yet.
    ///
    /// The order matters: the cache is free, batching is the biggest win when it
    /// applies, and coalescing catches what is left.
    pub async fn call(&self, endpoint: &str, query_json: &str) -> Result<String, NcmError> {
        self.call_in_full(endpoint, query_json, false).await
    }

    /// [`Self::call`], but never answered from a response already held.
    ///
    /// For the one thing a cache cannot serve: *"has the account accepted the
    /// write I just made?"*. [`crate::cache::ResponseCache::invalidate_for`] drops
    /// what a write disturbs, so an ordinary `call` after a write is usually right
    /// — but "usually" is the wrong standard for a reconcile, and there are two
    /// ways it is not right. A write that never passed through this isolate
    /// invalidates nothing: the `remote` transport, the resolver's own `ureq` path,
    /// another device, the web. And nothing invalidates an edit made elsewhere at
    /// all, while `playlist_detail` keeps being served from a 24-hour stale window.
    /// Both read to the user as a playlist that will not update.
    ///
    /// Only the *read* is skipped. The answer is stored as usual, `batch` and
    /// `inflight` still apply — sharing a request that is already on its way is
    /// not the same as being handed an old answer — and nothing here bypasses the
    /// throttle. So this costs exactly one round trip, and only where a caller has
    /// a reason to know that what it holds may be behind.
    ///
    /// Use it for a post-write reconcile and for re-reading a list a user has been
    /// away from; never on a hot path, and never for metadata, which does not
    /// change. `src/views/PlayList/PlayListView.vue` is the caller this exists for.
    pub async fn call_fresh(&self, endpoint: &str, query_json: &str) -> Result<String, NcmError> {
        self.call_in_full(endpoint, query_json, true).await
    }

    async fn call_in_full(
        &self,
        endpoint: &str,
        query_json: &str,
        fresh: bool,
    ) -> Result<String, NcmError> {
        let key = self.cache.key(endpoint, query_json);
        if let Some(key) = &key {
            // A fresh read takes no claim on the entry, so there is nothing to
            // release: `get` is what hands out the stale-refresh claim, and it is
            // exactly what is skipped here.
            match if fresh { None } else { self.cache.get(key) } {
                Some(cache::Hit::Fresh(body)) => return Ok(body.to_string()),
                Some(cache::Hit::Stale(body)) => {
                    // Answer now, refresh behind. The refresh is deliberately
                    // not awaited and its result is dropped: it exists to put a
                    // fresh entry in the cache for the *next* caller, and making
                    // this one wait for it would defeat the entire point.
                    //
                    // Spawned rather than run inline for the same reason it is
                    // not awaited — if this call's future is dropped the moment
                    // it returns, an inline refresh would be cancelled with it.
                    self.spawn_refresh(endpoint, query_json);
                    return Ok(body.to_string());
                }
                None => {}
            }
        }

        let out = self.fetch(endpoint, query_json, key).await?;

        // A write may have invalidated a list the app is caching. Only on
        // success: a failed `like` changed nothing, and dropping the entry would
        // cost a refetch to arrive at the same answer.
        if is_success(&out) {
            self.cache.invalidate_for(endpoint);
        }
        Ok(out)
    }

    /// The uncached path: batch, else coalesce, else go.
    async fn fetch(
        &self,
        endpoint: &str,
        query_json: &str,
        key: Option<cache::CacheKey>,
    ) -> Result<String, NcmError> {
        // Batched first: it is the only layer that can turn N calls into one
        // request, and each waiter comes back with its own slice under its own
        // cache key, so the entries it populates are exactly the ones a
        // subsequent unbatched call would look for.
        if let Some(plan) = batch::plan(endpoint, query_json) {
            let out = self
                .batcher
                .run(&plan, |query| self.call_uncached(endpoint, query))
                .await
                .map_err(NcmError::Script)?;
            if let Some(key) = key {
                self.cache.put(key, &out);
            }
            return Ok(out);
        }

        // Coalescing is gated on cacheability, which is the same question asked
        // once: an answer that may be remembered belongs to a read-only,
        // idempotent call, so two callers may share one request.
        if let Some(key) = key {
            let (out, led) = self
                .inflight
                .run(key.id(), || {
                    self.call_uncached(endpoint, query_json.to_owned())
                })
                .await
                .map_err(NcmError::Script)?;
            // Only the caller that actually made the request stores it. The
            // others hold the same bytes, and `playlist_track_all` reaches
            // megabytes — re-inserting it per waiter would copy it that many
            // times to no effect.
            if led {
                self.cache.put(key, &out);
            }
            return Ok(out);
        }

        self.call_uncached(endpoint, query_json.to_owned())
            .await
            .map_err(NcmError::Script)
    }

    /// Warm an endpoint's answer into the cache without waiting for it.
    ///
    /// For the case no amount of transport tuning can fix: a request issued at
    /// the exact moment its answer is needed costs a round trip, and across an
    /// idle gap it costs a handshake as well. Asking a little earlier — while the
    /// current track still has a minute to run, while the pointer is resting on a
    /// playlist card — costs the same request at a moment when nobody is waiting.
    ///
    /// Returns immediately, and is safe to call speculatively and often. Three
    /// things make it so, in order of how much they matter:
    ///
    /// * **It is dropped, never queued.** A permit is tried rather than awaited,
    ///   so a guess that cannot start now is abandoned. Work nobody is waiting
    ///   for has no business holding a place in a queue.
    /// * **It disappears when the client is being paced.** The same refusal that
    ///   installs pacing is what would put this in front of a real request.
    /// * **It is capped well below the per-host concurrency ceiling**, so the
    ///   foreground always has connections available.
    ///
    /// Only meaningful for a cacheable endpoint; anything else returns without
    /// doing work. `song_url_v1` is deliberately not one — a signed URL expires —
    /// so pre-resolving playback belongs to the layer that holds the resolved
    /// source, not here. What this *is* for is the rest of what a track change
    /// needs: `lyric_new` and `song_detail`.
    pub fn prefetch(&self, endpoint: &str, query_json: &str) {
        let Some(key) = self.cache.key(endpoint, query_json) else {
            return;
        };
        // Already held and fresh: nothing to do. A stale entry is left alone
        // too — `get` would have claimed the refresh, and doing it here would
        // race that.
        if matches!(self.cache.get(&key), Some(cache::Hit::Fresh(_))) {
            return;
        }
        let Some(permit) = self.speculation_permit() else {
            return;
        };

        let context = self.context.clone();
        let cache = self.cache.clone();
        let batcher = self.batcher.clone();
        let endpoint = endpoint.to_owned();
        let query_json = query_json.to_owned();
        tokio::spawn(async move {
            let _permit = permit;
            // Batched like any other call, which matters more here than
            // anywhere: `hintTrack` fires for the current track and the next
            // two, so three `song_detail` hints land in the same instant and
            // become one request instead of three. A real call arriving in the
            // same window joins them.
            let planned = batch::plan(&endpoint, &query_json);
            let result = match &planned {
                Some(plan) => batcher.run(plan, |q| call_in(&context, &endpoint, q)).await,
                None => call_in(&context, &endpoint, query_json).await,
            };
            match result {
                Ok(body) => cache.put(key, &body),
                // A prefetch that fails costs nothing: the real call will run
                // exactly as it would have.
                Err(e) => log::debug!(target: "ncm-core", "prefetch of {endpoint} failed: {e}"),
            }
        });
    }

    /// A permit for work nobody is waiting for, or `None` if there is no room
    /// for it right now.
    fn speculation_permit(&self) -> Option<tokio::sync::OwnedSemaphorePermit> {
        if self.http.is_strained() {
            // The client is already being pushed back on. Adding speculative
            // traffic to a burst that is being refused makes the refusals worse
            // and delays the calls that matter.
            return None;
        }
        self.speculation.clone().try_acquire_owned().ok()
    }

    /// Refetch a stale entry in the background, so the *next* caller finds it
    /// fresh.
    ///
    /// Detached on purpose. The caller that triggered this has already been
    /// answered from the stale copy and is about to return, so awaiting the
    /// refresh — or even running it inline — would either make it wait or get
    /// the refresh cancelled along with its future.
    ///
    /// Everything it needs is cheap to clone: `AsyncContext` is a handle onto
    /// the runtime, and the cache is behind an `Arc` for exactly this. The
    /// isolate outlives the task because dropping `NcmCore` drops the runtime,
    /// and `drive` completes when it does.
    fn spawn_refresh(&self, endpoint: &str, query_json: &str) {
        // Shares the speculation budget with `prefetch`, for the same reason: the
        // caller has already been answered, so this must never be in front of a
        // request someone is waiting on. When there is no room the stale entry
        // simply stays stale and the next caller past the TTL claims the refresh
        // again — which is exactly what `put_failed` leaves behind too.
        let Some(permit) = self.speculation_permit() else {
            self.cache.release_refresh(endpoint, query_json);
            return;
        };

        let context = self.context.clone();
        let cache = self.cache.clone();
        let endpoint = endpoint.to_owned();
        let query_json = query_json.to_owned();

        tokio::spawn(async move {
            let _permit = permit;
            // Rebuilt rather than passed in: `CacheKey` borrows nothing, but the
            // policy lookup is a match on a string and costs less than plumbing
            // it through.
            let Some(key) = cache.key(&endpoint, &query_json) else {
                return;
            };
            // Not batched and not coalesced: a refresh is nobody's critical
            // path, and joining a batch window would make a real caller wait on
            // it. `refreshing` on the entry is what keeps this to one at a time.
            match call_in(&context, &endpoint, query_json).await {
                Ok(body) => cache.put(key, &body),
                Err(e) => {
                    // The stale entry stays served until its window closes,
                    // which is the whole point — a failed refresh must not turn
                    // into a failed page.
                    log::debug!(
                        target: "ncm-core",
                        "background refresh of {endpoint} failed, keeping the stale answer: {e}"
                    );
                    cache.put_failed(key);
                }
            }
        });
    }

    /// One trip through the isolate, with nothing in front of it.
    ///
    /// Takes the query by value because the callers above hand it a query they
    /// built — a merged id list, in the batched case — rather than the one they
    /// were given.
    async fn call_uncached(&self, endpoint: &str, query_json: String) -> Result<String, String> {
        call_in(&self.context, endpoint, query_json).await
    }
}

/// Invoke `__ncmProtocol.call` in `context`.
///
/// Free function rather than a method so the background refresh can use it with
/// a cloned context instead of borrowing `self` into a detached task.
async fn call_in(
    context: &AsyncContext,
    endpoint: &str,
    query_json: String,
) -> Result<String, String> {
    let endpoint = endpoint.to_owned();
    context
        .async_with(async move |ctx| -> Result<String, String> {
            let proto: Object = ctx
                .globals()
                .get("__ncmProtocol")
                .map_err(|e| explain(&ctx, e))?;
            let call: Function = proto.get("call").map_err(|e| explain(&ctx, e))?;
            let promise: Promise = call
                .call((
                    rquickjs::function::This(proto),
                    endpoint.as_str(),
                    query_json.as_str(),
                ))
                .map_err(|e| explain(&ctx, e))?;
            promise
                .into_future::<String>()
                .await
                .map_err(|e| explain(&ctx, e))
        })
        .await
}

/// Whether an envelope reports a call that actually went through.
///
/// Reads the shape rather than parsing the body, for the same reason
/// `cache::is_storable` does: this runs on every call, including the ones that
/// return megabytes.
fn is_success(envelope: &str) -> bool {
    envelope.starts_with(r#"{"ok":true"#)
}

/// Turn a QuickJS error into a message safe to log.
///
/// `rquickjs::Error::Exception` carries no detail on its own — the thrown value
/// stays on the context — so the value has to be pulled with `Ctx::catch`
/// before it is discarded. Without this every script failure reads
/// "Exception generated by QuickJS", which is useless for a bundle this size.
fn explain(ctx: &rquickjs::Ctx<'_>, e: rquickjs::Error) -> String {
    if !matches!(e, rquickjs::Error::Exception) {
        return redact(&e.to_string());
    }
    let thrown = ctx.catch();
    let described = match thrown.as_exception() {
        Some(ex) => {
            let msg = ex.message().unwrap_or_else(|| "<no message>".into());
            match ex.stack() {
                Some(stack) if !stack.is_empty() => format!("{msg}\n{stack}"),
                _ => msg,
            }
        }
        None => thrown
            .try_into_string()
            .ok()
            .and_then(|s| s.to_string().ok())
            .unwrap_or_else(|| "<non-Error thrown>".into()),
    };
    redact(&described)
}

/// Strip anything credential-shaped before it reaches a log.
///
/// Mirrors `source_resolver::redact` in the audio backend; defence in depth,
/// not a substitute for not putting secrets in messages to begin with.
///
/// Redacts *values*, not the words around them. The previous version replaced
/// every whitespace-delimited chunk containing a sensitive word, and upstream's
/// `util/request.js` logs its failures as `console.log('[ERR]', answer)` — one
/// unspaced JSON blob ending in `"cookie":[]`. So the whole tail went, taking
/// the only interesting part with it: `transport error [redacted]` instead of
/// `transport error (connect) …`. Key names are not secret and are what make a
/// log line searchable; the value after them is what must never be written.
pub fn redact(text: &str) -> String {
    // Substring match, not token match: `__csrf`, `MUSIC_U` and
    // `anonymous_token` all carry their marker mid-word, and a false positive
    // costs one hidden value rather than a hidden line.
    const SENSITIVE: [&str; 8] = [
        "music_u",
        "music_a",
        "cookie",
        "csrf",
        "token",
        "sskey",
        "sessionid",
        "password",
    ];
    /// Between a key and its value: `k=v`, `"k": "v"`, `k v`.
    const SEPARATORS: [char; 6] = ['=', ':', '"', '\'', ' ', '\t'];
    /// Ends a value. `[`, `{` and `(` are here so a structured value is stepped
    /// into rather than swallowed — its own sensitive leaves get redacted on
    /// their own terms, and a stack frame like `at getToken (bundle.js:1)`
    /// keeps the part that says where.
    const TERMINATORS: [char; 13] = [
        ';', ',', '&', '"', '\'', '}', ']', ')', '[', '{', '(', '\\', ' ',
    ];

    let lower = text.to_ascii_lowercase();
    let mut out = String::with_capacity(text.len());
    let mut cursor = 0;

    while cursor < text.len() {
        let Some((start, len)) = SENSITIVE
            .iter()
            .filter_map(|key| lower[cursor..].find(key).map(|at| (cursor + at, key.len())))
            .min_by_key(|(start, _)| *start)
        else {
            break;
        };
        let hit = start + len;

        out.push_str(&text[cursor..hit]);
        cursor = hit;

        // Step over the separator run, then take everything up to the first
        // terminator as the value.
        let after_sep = text[cursor..]
            .find(|c: char| !SEPARATORS.contains(&c))
            .map(|at| cursor + at)
            .unwrap_or(text.len());
        let value_end = text[after_sep..]
            .find(|c: char| TERMINATORS.contains(&c) || c.is_whitespace())
            .map(|at| after_sep + at)
            .unwrap_or(text.len());

        out.push_str(&text[cursor..after_sep]);
        if value_end > after_sep {
            out.push_str("[redacted]");
        }
        cursor = value_end;
    }

    out.push_str(&text[cursor..]);
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn redacts_credential_values_and_keeps_their_keys() {
        assert_eq!(
            redact("failed for MUSIC_U=abc123 and csrf=xyz"),
            "failed for MUSIC_U=[redacted] and csrf=[redacted]"
        );
        assert_eq!(redact("transport error (Dns)"), "transport error (Dns)");
        assert_eq!(
            redact(r#"{"anonymous_token": "abc.def"}"#),
            r#"{"anonymous_token": "[redacted]"}"#
        );
        assert_eq!(
            redact("Cookie: MUSIC_U=deadbeef; __csrf=1234; os=pc"),
            "Cookie: [redacted]; __csrf=[redacted]; os=pc"
        );
    }

    /// The line this exists for. Upstream's `util/request.js` reports a failure
    /// as `console.log('[ERR]', answer)`, and `answer` serializes to one
    /// unspaced JSON blob whose last field is `"cookie"`. Redacting by
    /// whitespace-delimited chunk therefore erased the error kind — the only
    /// part worth logging — and left `transport error [redacted]`.
    #[test]
    fn an_error_envelope_survives_redaction() {
        let line = r#"[ERR] {"status":502,"body":{"code":502,"msg":"httpRequest: transport error (connect) via interface.music.163.com"},"cookie":[]}"#;
        assert_eq!(redact(line), line);
    }

    /// Structure is stepped into, not swallowed: a cookie array keeps its
    /// shape and loses only the values inside it.
    #[test]
    fn redaction_reaches_inside_a_cookie_array() {
        assert_eq!(
            redact(r#"{"cookie":["MUSIC_U=secret; Max-Age=0","__csrf=nope; Path=/"]}"#),
            r#"{"cookie":["MUSIC_U=[redacted]; Max-Age=0","__csrf=[redacted]; Path=/"]}"#
        );
    }

    /// Evaluate an expression inside a built isolate. Same-crate tests only —
    /// this reaches the private context on purpose rather than widening the
    /// public API for a test.
    async fn eval(core: &NcmCore, src: &'static str) -> String {
        core.context
            .async_with(async move |ctx| {
                ctx.eval::<String, _>(src).map_err(|e| explain(&ctx, e))
            })
            .await
            .expect("eval failed")
    }

    /// The form encoding produced by the `URLSearchParams` shim goes on the
    /// wire *inside the signed xeapi payload* (`buildXeapiPlaintext` base64s
    /// it), so it has to match Node byte for byte. These expectations are what
    /// Node 20 produces — a divergence here is a protocol change that no local
    /// test would otherwise catch, only a server-side rejection.
    #[tokio::test]
    async fn url_search_params_matches_node_form_encoding() {
        let core = NcmCore::offline().await.expect("isolate");

        // Space is '+', '+' is escaped, and of the characters
        // encodeURIComponent leaves alone only '*' survives.
        assert_eq!(
            eval(
                &core,
                r#"new URLSearchParams({a:"hello world",b:"a+b",c:"!~*()'",d:"中文"}).toString()"#
            )
            .await,
            "a=hello+world&b=a%2Bb&c=%21%7E*%28%29%27&d=%E4%B8%AD%E6%96%87"
        );

        // Node stringifies undefined/null rather than dropping the key.
        assert_eq!(
            eval(
                &core,
                r#"new URLSearchParams({level:undefined,id:347230,x:null}).toString()"#
            )
            .await,
            "level=undefined&id=347230&x=null"
        );

        // Keys are encoded with the same rules as values.
        assert_eq!(
            eval(&core, r#"new URLSearchParams({"k e y":"v&v=v"}).toString()"#).await,
            "k+e+y=v%26v%3Dv"
        );
    }

    /// The Buffer shim carries every byte the crypto layer touches. Round-trip
    /// the encodings that appear in `util/crypto.js`, including multi-byte
    /// UTF-8 — the protocol signs UTF-8 bytes of JSON that routinely contains
    /// CJK.
    #[tokio::test]
    async fn buffer_shim_round_trips_encodings() {
        let core = NcmCore::offline().await.expect("isolate");

        assert_eq!(
            eval(&core, r#"Buffer.from("中文abc","utf8").toString("hex")"#).await,
            "e4b8ade69687616263"
        );
        assert_eq!(
            eval(&core, r#"Buffer.from("e4b8ad","hex").toString("utf8")"#).await,
            "中"
        );
        assert_eq!(
            eval(&core, r#"Buffer.from("中文","utf8").toString("base64")"#).await,
            "5Lit5paH"
        );
        assert_eq!(
            eval(&core, r#"Buffer.from("5Lit5paH","base64").toString("utf8")"#).await,
            "中文"
        );
        // latin1 is how forge-style binary strings cross the shim boundary.
        assert_eq!(
            eval(
                &core,
                r#"Buffer.from(String.fromCharCode(0,255,128),"latin1").toString("hex")"#
            )
            .await,
            "00ff80"
        );
        assert_eq!(
            eval(
                &core,
                r#"String(Buffer.concat([Buffer.from("ab"),Buffer.from("cd")]).toString("utf8"))"#
            )
            .await,
            "abcd"
        );
        // Node's Buffer#slice is a view, not a copy like Array#slice.
        assert_eq!(
            eval(
                &core,
                r#"(()=>{const b=Buffer.from("abcd");b.slice(1,3)[0]=120;return b.toString("utf8")})()"#
            )
            .await,
            "axcd"
        );
    }

    /// `util/ncbl.js` — the NCBL log envelope behind `scrobble_v1` — is the only
    /// thing in the package that reads or writes little-endian integers, and it
    /// reaches them on the first two lines of `encryptNCBL`. The shim carried
    /// only the big-endian pair, so every `scrobble_v1` call answered
    /// `502 {"msg":"请求异常: not a function"}`: QuickJS's message for invoking a
    /// non-callable, which names neither `readUInt32LE` nor the file it is in,
    /// and which the endpoint's own `catch` then reported as a transport
    /// failure.
    ///
    /// Byte order is pinned against literal hex rather than round-tripped
    /// through the pair. A read and a write that are consistently wrong
    /// round-trip perfectly and still build a ChaCha20 keystream Netease
    /// rejects — with a `code: 200` on the upload, since the server only reports
    /// which files it accepted.
    #[tokio::test]
    async fn buffer_shim_carries_the_little_endian_accessors_ncbl_needs() {
        let core = NcmCore::offline().await.expect("isolate");

        // Low byte first, and the return is the next offset, as Node's are.
        assert_eq!(
            eval(
                &core,
                r#"(()=>{const b=Buffer.alloc(8);const a=b.writeUInt32LE(0x01020304,0);const c=b.writeUInt16LE(0x0506,4);return `${b.toString("hex")} ${a} ${c}`})()"#
            )
            .await,
            "0403020106050000 4 6"
        );

        // Reads are unsigned. `chachaBlock` feeds them straight into a
        // `Uint32Array`, so a signed `0xffffffff` would survive as -1 there and
        // only diverge once it was added to another word.
        assert_eq!(
            eval(
                &core,
                r#"(()=>{const h=Buffer.from("ffffffff0102","hex");return `${h.readUInt32LE(0)} ${h.readUInt16LE(4)}`})()"#
            )
            .await,
            "4294967295 513"
        );

        // The nonce is `uuid.subarray(0, 12)` and a frame is
        // `compressed.subarray(off, off + maxFrame)` — both views. The accessors
        // must index through the view; a `DataView` over `this.buffer` would
        // read from the wrong place for any non-zero `byteOffset`.
        assert_eq!(
            eval(
                &core,
                r#"(()=>{const b=Buffer.from("00000000aabbccdd","hex").subarray(4);return String(b.readUInt32LE(0))})()"#
            )
            .await,
            "3721182122"
        );
    }

    /// The whole NCBL path behind `scrobble_v1`, with the upload intercepted
    /// before it reaches a socket.
    ///
    /// Worth the machinery because nothing else in the bundle resembles it.
    /// `scrobble_v1` skips the weapi/eapi/xeapi envelope entirely and builds its
    /// own in `util/ncbl.js`: hand-rolled ChaCha20 over the Buffer shim's
    /// little-endian accessors, a 256-bit RSA key wrap over BigInt, gzip, a
    /// binary multipart body, and `axios` called *bare*. Every one of those is
    /// reachable only from here.
    ///
    /// Stubbing `__ncm_host.httpRequest` is what makes it offline and
    /// deterministic: the shims look their host ops up by property at call time,
    /// on the very object the bundle closed over, so replacing one intercepts the
    /// real code path without touching the bundle. The stub answers like the
    /// server does — echoing back the filename it was sent — so both uploads run
    /// and the module reports its success rather than stopping at PLV.
    ///
    /// This is the test that would have caught either half of the `502 请求异常:
    /// not a function` bug, and it asserts against the bytes on the way out
    /// rather than against a mock's own expectations.
    #[tokio::test]
    async fn the_ncbl_upload_behind_scrobble_v1_builds_and_is_sent() {
        let core = NcmCore::offline().await.expect("isolate");

        assert_eq!(
            eval(
                &core,
                r#"(()=>{
                  const h = globalThis.__ncm_host;
                  globalThis.__sent = [];
                  h.httpRequest = (cfg) => {
                    // The part headers are ASCII and the NCBL payload follows
                    // them, so one latin1 decode of the head reaches both.
                    const head = Buffer.from(cfg.body.subarray(0, 400)).toString("latin1");
                    const magicAt = head.indexOf("NCBL");
                    globalThis.__sent.push({
                      method: cfg.method,
                      url: cfg.url,
                      contentType: cfg.headers["Content-Type"],
                      magicAt,
                      // Read out of the real header, so a byte order that is
                      // consistently wrong still fails here.
                      version: magicAt < 0 ? -1 : cfg.body.readUInt32LE(magicAt + 4),
                      headerLen: magicAt < 0 ? -1 : cfg.body.readUInt16LE(magicAt + 8),
                      bytes: cfg.body.length,
                    });
                    const name = /filename="([^"]+)"/.exec(head);
                    const body = JSON.stringify({
                      code: 200,
                      data: { successfiles: [name ? name[1] : ""] },
                    });
                    return Promise.resolve({ status: 200, headers: {}, body: Buffer.from(body) });
                  };
                  return "ok";
                })()"#
            )
            .await,
            "ok"
        );

        let out: serde_json::Value = serde_json::from_str(
            &core
                .call(
                    "scrobble_v1",
                    r#"{"id":"347230","time":30,"total":268,"cookie":"MUSIC_U=not-a-real-token; os=pc"}"#,
                )
                .await
                .expect("call failed"),
        )
        .expect("not JSON");

        // Asserted first and by name: a shim gap surfaces as this exact message,
        // and reporting it as itself is the difference between a five-minute fix
        // and re-deriving which layer broke.
        let msg = out["body"]["msg"].as_str().unwrap_or_default();
        assert!(
            !msg.contains("not a function"),
            "the NCBL path reached something the shims do not provide: {msg}"
        );
        assert_eq!(out["body"]["code"], 200, "scrobble_v1 failed: {}", out["body"]);

        let sent: serde_json::Value =
            serde_json::from_str(&eval(&core, r#"JSON.stringify(globalThis.__sent)"#).await)
                .expect("not JSON");
        let sent = sent.as_array().expect("no uploads recorded");

        // PLV then PLD, two independent uploads. One would mean the module
        // stopped early and reported a success it did not have.
        assert_eq!(sent.len(), 2, "expected PLV and PLD, got {sent:?}");
        for one in sent {
            assert_eq!(one["method"], "POST");
            assert_eq!(
                one["url"],
                "https://clientlog3.music.163.com/api/clientlog/encrypt/upload?multiupload=true"
            );
            // `axios` fills in a Content-Type when the caller omits one; here the
            // caller sets it, boundary included, and the body is built around
            // that exact boundary.
            let ct = one["contentType"].as_str().unwrap_or_default();
            assert!(
                ct.starts_with("multipart/form-data; boundary="),
                "unexpected content type: {ct}"
            );
            // NCBL magic, then version 3 and the header length — both read back
            // little-endian out of the header the shim wrote.
            assert!(one["magicAt"].as_i64().unwrap_or(-1) > 0, "no NCBL magic in the body");
            assert_eq!(one["version"], 3);
            // 70 fixed bytes plus the 4-byte meta block header and its
            // ciphertext, which is the metadata JSON's own length.
            assert!(
                one["headerLen"].as_u64().unwrap_or(0) > 74,
                "implausible header length: {}",
                one["headerLen"]
            );
            assert!(one["bytes"].as_u64().unwrap_or(0) > 400, "implausibly small upload");
        }
    }

    /// Spot-check the host crypto ops against known vectors, through the same
    /// `node:crypto` surface the protocol layer uses.
    #[tokio::test]
    async fn crypto_shim_matches_known_vectors() {
        let core = NcmCore::offline().await.expect("isolate");

        assert_eq!(
            eval(
                &core,
                r#"Buffer.from(globalThis.__ncm_host.md5(Buffer.from("abc"))).toString("hex")"#
            )
            .await,
            "900150983cd24fb0d6963f7d28e17f72"
        );
        assert_eq!(
            eval(
                &core,
                r#"Buffer.from(globalThis.__ncm_host.sha256(Buffer.from("abc"))).toString("hex")"#
            )
            .await,
            "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad"
        );
        // RFC 4231 test case 1.
        assert_eq!(
            eval(
                &core,
                r#"Buffer.from(globalThis.__ncm_host.hmacSha256(Buffer.alloc(20,0x0b),Buffer.from("Hi There"))).toString("hex")"#
            )
            .await,
            "b0344c61d8db38535ca8afceaf0bf12b881dc200c9833da726e9376c2e32cff7"
        );
        // AES-128-ECB round trip, which is what pins the PKCS#7 padding Node
        // applies by default and the protocol layer relies on.
        assert_eq!(
            eval(
                &core,
                r#"(()=>{const k=Buffer.from("0123456789abcdef");const c=globalThis.__ncm_host.aesEcbEncrypt(k,Buffer.from("hello world"));return Buffer.from(globalThis.__ncm_host.aesEcbDecrypt(k,c)).toString("utf8")})()"#
            )
            .await,
            "hello world"
        );
        // GCM round trip including the separately-surfaced auth tag.
        assert_eq!(
            eval(
                &core,
                r#"(()=>{const k=Buffer.from("0123456789abcdef");const iv=Buffer.alloc(12,7);const r=globalThis.__ncm_host.aesGcmEncrypt(k,iv,Buffer.from("secret"));return Buffer.from(globalThis.__ncm_host.aesGcmDecrypt(k,iv,r.ciphertext,r.tag)).toString("utf8")})()"#
            )
            .await,
            "secret"
        );
        // X25519: both sides must derive the same shared secret.
        assert_eq!(
            eval(
                &core,
                r#"(()=>{const h=globalThis.__ncm_host;const a=h.x25519Generate();const b=h.x25519Generate();const s1=Buffer.from(h.x25519Diffie(a.privateKey,b.publicKey)).toString("hex");const s2=Buffer.from(h.x25519Diffie(b.privateKey,a.publicKey)).toString("hex");return s1===s2?"match":s1+" != "+s2})()"#
            )
            .await,
            "match"
        );
        // gzip round trip.
        assert_eq!(
            eval(
                &core,
                r#"Buffer.from(globalThis.__ncm_host.gunzip(globalThis.__ncm_host.gzip(Buffer.from("中文 payload")))).toString("utf8")"#
            )
            .await,
            "中文 payload"
        );
    }
}
