[[permission]]
identifier = "allow-audio-get-analysis-spectrum"
description = "Enables the audio_get_analysis_spectrum command without any pre-configured scope."
commands.allow = ["audio_get_analysis_spectrum"]

[[permission]]
identifier = "deny-audio-get-analysis-spectrum"
description = "Denies the audio_get_analysis_spectrum command without any pre-configured scope."
commands.deny = ["audio_get_analysis_spectrum"]
