[[permission]]
identifier = "allow-audio-toggle-playback"
description = "Enables the audio_toggle_playback command without any pre-configured scope."
commands.allow = ["audio_toggle_playback"]

[[permission]]
identifier = "deny-audio-toggle-playback"
description = "Denies the audio_toggle_playback command without any pre-configured scope."
commands.deny = ["audio_toggle_playback"]
