[[permission]]
identifier = "allow-queue_get_all"
description = "Enables the queue_get_all command without any pre-configured scope."
commands.allow = ["queue_get_all"]

[[permission]]
identifier = "deny-queue_get_all"
description = "Denies the queue_get_all command without any pre-configured scope."
commands.deny = ["queue_get_all"]